FROM kapacitor:1.1.1

ENV DATABASE=$DATABASE
ENV RETENTION_POLICY=RETENTION_POLICY
ENV ALERT=$ALERT
ENV VARS=VARS
ENV KAPACITOR_URL=KAPACITOR_URL
ENV FUNCTION=$FUNCTION

COPY kapacitorAlertLoader.sh /kapacitorAlertLoader.sh
ENTRYPOINT ["/kapacitorAlertLoader.sh"]
